# Generated by Django 5.2.7 on 2025-10-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_intervention_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Binôme',
                'verbose_name_plural': 'Binômes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BinomeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Binôme - état',
                'verbose_name_plural': 'Binômes - états',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CallTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('offset_weeks', models.IntegerField(default=0)),
                ('recurrence_months', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Template d'appel",
                'verbose_name_plural': "Templates d'appel",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='FieldVisitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('offset_weeks', models.IntegerField(default=0)),
                ('recurrence_months', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Template de visite terrain',
                'verbose_name_plural': 'Templates de visite terrain',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BinomePause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('binome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='quality.binome')),
            ],
            options={
                'verbose_name': 'Pause de binôme',
                'verbose_name_plural': 'Pauses de binôme',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='binome',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='binomes', to='quality.binomestate'),
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('scheduled_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('binome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='quality.binome')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='quality.calltemplate')),
            ],
            options={
                'verbose_name': 'Appel',
                'verbose_name_plural': 'Appels',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddField(
            model_name='binome',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binomes', to='quality.client'),
        ),
        migrations.AddField(
            model_name='binome',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binomes', to='quality.employee'),
        ),
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('scheduled_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('binome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_visits', to='quality.binome')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_visits', to='quality.fieldvisittemplate')),
            ],
            options={
                'verbose_name': 'Visite terrain',
                'verbose_name_plural': 'Visites terrain',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='binome',
            unique_together={('client', 'employee', 'state')},
        ),
    ]
