# Generated by Django 5.2.7 on 2025-10-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binome',
            name='state',
            field=models.CharField(choices=[('Conforme', 'Conforme'), ('Non conforme', 'Non conforme'), ('À appeler', 'À appeler')], default='À appeler', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='binome',
            unique_together={('client', 'employee')},
        ),
        migrations.DeleteModel(
            name='BinomeState',
        ),
    ]
