# Generated by Django 5.2.7 on 2025-10-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_alter_binome_state_alter_binome_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binome',
            name='state',
            field=models.CharField(choices=[('Conforme', 'Conforme'), ('Non conforme', 'Non conforme'), ('À appeler', 'À appeler'), ('En retard', 'En retard')], default='À appeler', max_length=20),
        ),
    ]
