# Generated by Django 5.2.7 on 2025-10-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_alter_binome_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltemplate',
            name='type',
            field=models.CharField(choices=[('Client', 'Client'), ('Employé', 'Employé')], default='Client', max_length=20),
        ),
    ]
