# Generated by Django 5.2.7 on 2025-10-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_calltemplate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltemplate',
            name='offset_weeks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='calltemplate',
            name='type',
            field=models.CharField(choices=[('Client', 'Client'), ('Employé', 'Employé'), ('Visite', 'Visite'), ('RDV', 'RDV')], default='Client', max_length=20),
        ),
        migrations.DeleteModel(
            name='FieldVisit',
        ),
        migrations.DeleteModel(
            name='FieldVisitTemplate',
        ),
    ]
