# Generated by Django 5.2.7 on 2025-10-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_alter_calltemplate_offset_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='report',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='calltemplate',
            name='offset_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
