# Generated by Django 5.2.7 on 2025-10-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_call_report_alter_calltemplate_offset_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
