# Generated by Django 5.2.7 on 2025-12-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_alter_call_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='binome',
            name='rhythm',
            field=models.IntegerField(choices=[(1, 'Hebdomadaire (Standard)'), (2, 'Bimensuel (x2)'), (4, 'Mensuel (x4)')], default=1, verbose_name="Rythme d'intervention"),
        ),
    ]
