# Generated by Django 5.2.7 on 2025-12-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_binome_rhythm'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='outcome',
            field=models.CharField(blank=True, choices=[('Conforme', 'Conforme'), ('Non conforme', 'Non conforme'), ('Reprogrammé', 'Reprogrammé')], max_length=20, null=True, verbose_name="Issue de l'appel"),
        ),
    ]
