# Generated by Django 5.2.7 on 2025-12-05 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0009_call_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='created_next_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_call', to='quality.call', verbose_name='Appel suivant créé'),
        ),
    ]
