# Generated by Django 5.2.7 on 2025-12-05 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0010_call_created_next_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='previous_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_calls', to='quality.call', verbose_name='Appel précédent'),
        ),
    ]
