# Generated by Django 5.2.7 on 2025-12-05 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0011_call_previous_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_history', to='quality.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_history', to='quality.employee')),
            ],
            options={
                'verbose_name': 'Historique Client-Intervenant',
                'verbose_name_plural': 'Historiques Client-Intervenant',
                'ordering': ['-started_at'],
                'unique_together': {('client', 'employee', 'started_at')},
            },
        ),
    ]
